### ISSUE TITLE
Delay2 VST Generation Errors

### ISSUE THREAD

**Issue by cerkut** [SMCFY/smc7_group2_project#2]
I see two issues:

1. Q does not depend on the fs, so may not be reset 
2. in vibrato, you may need to create a y vector of appropriate size (buffer,2)?

Still checking ...

There are additional issues in passing Strings from the GUI to the class that cause error:
%set.Effect is called every time a new effect is selected 
        function set.Effect(obj, effect)
             % obj.Effect = effect;
        end
        
% set.Effect is called every time a new effect is selected 
        function set.Filter(obj, filter)
             % obj.Filter = filter;
        end
and
%             switch obj.guitar
%                 case 'Connected'
%                     x(:,2) = x(:,1);
%                 case 'Not Connected'
%             end

Disabling all the above compiles the plugin. I'll check for fixes and maybe issue a pull request.

**Comment by NikolajAndersson** [comment]
Great thanks! 
For the vibrato: Is the buffer for the vibrato not big enough? It's using the obj.Buffer to store and manipulate the signal.

For the switch cases and passing strings around: 
I saw that it gave a warning, but I couldn't figure out another way of doing it. Can you make enum{'stateOn','stateOff'} and use instead?

**Comment by cerkut** [comment]
for the vibrato: compiler offends when y is created dynamically in the function, you need to allocate memory.

For the switch cases and passing strings around: you need a helper class to handle the audio plugin UI enums. Check audiopluginexample.Strobe and its helper class audioexample.StrobeFillEnum by issuing

`edit audioexample.StrobeFillEnum audiopluginexample.Strobe`

See also https://se.mathworks.com/videos/enumeration-classes-in-r2010b-68983.html

**Comment by NikolajAndersson** [comment]
Thanks! I uploaded a new version to master now that can be validated and exported as .vst.
